#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 13 11:37:52 2021

cynthia data test

@author: sean
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
import vessel_metrics as vm
import glob, os

data_path = '/home/sean/Documents/Data/Wnt_Treatment/'
date = 'Nov2/'
files = os.listdir(data_path + date)

for f in files:
    temp_vol = vm.preprocess_czi(data_path+date, f, channel = 1)
        
plt.figure()
plt.imshow(temp_vol[25])

with CziFile(data_path + date+ f) as czi:
    image_arrays = czi.asarray()

slice_range = len(temp_vol)
slice_thickness = np.round(slice_range/2).astype(np.uint8)
reslice = vm.reslice_image(temp_vol,slice_thickness)
this_slice = reslice[0]

seg = vm.brain_seg(this_slice)

vm.overlay_segmentation(this_slice, seg)

label = cv2.imread('/home/sean/Pictures/Cynthia_test/label.png',0)

vm.overlay_segmentation(this_slice, label)

label[label>1] = 1

overlay = seg+label*2
plt.figure()
plt.imshow(overlay)

vm.jaccard(label, seg)

skel = skeletonize(label)
edges, bp = vm.find_branchpoints(skel)
_, edge_labels = cv2.connectedComponents(edges)

vm.overlay_segmentation(this_slice, edge_labels+label)
vm.overlay_segmentation(this_slice, label+skel)
