#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  8 13:17:34 2022

Cynthia 75 hpf

@author: sean
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
import vessel_metrics as vm
import glob, os
from cv2_rolling_ball import subtract_background_rolling_ball
from skimage.filters import meijering, hessian, frangi, sato
from skimage.morphology import skeletonize
from scipy.stats import ttest_ind

data_path = '/home/sean/Documents/vm_manuscript/raw_data/DMH410uM75hpf/Jan15/'

label_list = []
im_list = []
data_files = os.listdir(data_path)

reslice_list = []
for file in data_files:
    volume = vm.preprocess_czi(data_path,file)
    slice_range = len(volume)
    slice_thickness = np.round(slice_range/2).astype(np.uint8)
    reslice = vm.reslice_image(volume,slice_thickness)
    this_slice = reslice[0]
    reslice_list.append(this_slice)

seg_list = []
seg_count_auto_list = []
vd_auto_list = []
bpd_auto_list = []
vessel_length_auto = []
length_list_a = []
bpd_a_nz = []
mean_length_auto = []
for im in reslice_list:
    print(count)
    seg = vm.brain_seg(im)
    seg_list.append(seg.astype(np.uint8))
    
    label[label>0] = 1
    auto_skel = skeletonize(seg)
    edges_a, bp_a = vm.connect_segments(auto_skel)
    
    #edges_a, bp_a = vm.find_branchpoints(auto_skel)
    seg_count_a, edge_labels_a = cv2.connectedComponents(edges_a)
    
    seg_count_auto_list.append(seg_count_a)
    
    _, vessel_density_a = vm.vessel_density(im, seg, 16, 16)
    
    vessel_density_a = np.array(vessel_density_a)
    
    vessel_density_a_mean = np.mean(vessel_density_a[vessel_density_a>0])
    
    vd_auto_list.append(vessel_density_a_mean)
    
    bp_density_a = vm.branchpoint_density(auto_skel, seg)
    
    bpd_num_zeros_a = np.count_nonzero(bp_density_a == 0)
    
    bpd_a_nz.append(bpd_num_zeros_a)
    
    bpd_auto_list.append(np.mean(bp_density_a[np.nonzero(bp_density_a)]))
    
    _, length_auto = vm.vessel_length(edge_labels_a)
    
    mean_length_auto.append(np.mean(length_auto))

plt.figure(); plt.imshow(reslice_list[2])
