#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 14 11:42:00 2022

manual param validation

@author: sean
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
import vessel_metrics as vm
import glob, os
from cv2_rolling_ball import subtract_background_rolling_ball
from skimage.filters import meijering, hessian, frangi, sato
from skimage.morphology import skeletonize
from scipy.stats import ttest_ind

data_path = '/media/sean/SP PHD U3/from_home/vm_manuscript/SE4_manual_params/'
data_files = os.listdir(data_path)

num_segments = []
num_bp = []
for file in data_files:
    im = cv2.imread(data_path+file,0)
    seg = vm.brain_seg(im)
    skel, edges, bp = vm.skeletonize_vm(seg)
    seg_count, edge_labels = cv2.connectedComponents(edges.astype(np.uint8))
    bp_count, bp_labels = cv2.connectedComponents(bp.astype(np.uint8))
    
    num_segments.append(seg_count)
    num_bp.append(bp_count)
    