#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  8 11:46:32 2021

nabila data test

@author: sean
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
import vessel_metrics as vm
import glob, os
from timeit import default_timer as timer
from cv2_rolling_ball import subtract_background_rolling_ball
from skimage.filters import meijering, hessian, frangi, sato
from skimage.morphology import skeletonize
from scipy import stats
from scipy.spatial import distance
from skimage.draw import line
from copy import deepcopy

data_path = '/home/sean/Documents/vessel_metrics/data/'
file = 'nabila_emb1.czi'

ch0 = vm.preprocess_czi(data_path, file, channel = 0)
ch1 = vm.preprocess_czi(data_path, file, channel = 1)

plt.figure()
plt.imshow(ch0[15,:,:])

plt.figure()
plt.imshow(ch1[15,:,:])

ch0_proj = vm.czi_projection(ch0, axis = 0)
ch1_proj = vm.czi_projection(ch1, axis = 0)
###########################################################
#with CziFile(data_path + file) as czi:
#    image_arrays = czi.asarray()