#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 17 09:15:22 2022

seg versatility

@author: sean
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
import vessel_metrics as vm
import glob, os
from cv2_rolling_ball import subtract_background_rolling_ball
from skimage.filters import meijering, hessian, frangi, sato
from skimage.morphology import skeletonize

data_path = '/media/sean/SP PHD U3/from_home/vm_manuscript/seg_versatility/'

label_list = []
im_list = []
data_files = os.listdir(data_path)
data_files = [i for i in data_files if not '.' in i]

for file in data_files:
    label_list.append(cv2.imread(data_path+file+'/label.png',0))
    im_list.append(cv2.imread(data_path+file+'/img.png',0))
    
seg_list = []
conn_list = []
area_list = []
length_list = []
jacc_list = []
for im, label in zip(im_list, label_list):
    seg = vm.brain_seg(im, filter = 'meijering', thresh = 60)
    
    length, area, conn = vm.cal(label.astype(np.uint8), seg.astype(np.uint8))
    conn_list.append(conn)
    area_list.append(area)
    length_list.append(length)
    jacc_list.append(vm.jaccard(label, seg))
    
