#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 15 23:10:55 2022

vm methods figure

@author: sean
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
import vessel_metrics as vm
import glob, os
from cv2_rolling_ball import subtract_background_rolling_ball
from skimage.filters import meijering, hessian, frangi, sato
from skimage.morphology import skeletonize

data_path = '/home/sean/Documents/vm_manuscript/E1_combined/'
test_emb = 'Nov2_DMSO3'

im = cv2.imread(data_path+test_emb+'/img.png',0)
seg = vm.brain_seg(im)
skel = skeletonize(seg)
edges, bp = vm.connect_segments(skel)
_, edge_labels = cv2.connectedComponents(edges)

segment_number = 133

diam, mean_diam, viz = vm.visualize_vessel_diameter(edge_labels, segment_number, seg, im)

segment_inds = np.argwhere(edge_labels == segment_number)
segment = np.zeros_like(edge_labels)
segment[edge_labels==segment_number] = 1
this_point = segment_inds[44]
vx,vy = vm.tangent_slope(segment, this_point)
bx,by = vm.crossline_slope(vx,vy)
cross_length = 30
_, cross_index = vm.make_crossline(bx,by, this_point, cross_length)
cross_vals = vm.crossline_intensity(cross_index,im_preproc)
#viz, diameters = vm.whole_anatomy_diameter(im, seg, edge_labels)

im_preproc = vm.contrast_stretch(im)
im_preproc = vm.preprocess_seg(im_preproc)